#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

function prompt_spaceship_preexec {
  # Stop running prompt async jobs
  if [[ "${_SS_DATA[async]}" == "true" ]]; then
    async_flush_jobs "spaceship_section_worker"
  fi

  # TODO: separate hook for tim
  [[ $SPACESHIP_EXEC_TIME_SHOW == false ]] && return

  # The Timer is started here, but the end is taken in prompt_spaceship_precmd, as this
  # method is a precmd hook and runs right before the prompt gets rendered. So we
  # can calculate the duration there.
  SPACESHIP_EXEC_TIME_start=${EPOCHREALTIME}
}

prompt_spaceship_preexec "$@"
