#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

function prompt_spaceship_chpwd {
  if [[ "${_SS_DATA[async]}" == "true" ]]; then
    async_worker_eval "spaceship_section_worker" 'cd' "$PWD"
  fi

  run-ss-hook chpwd
}

typeset -ag ss_chpwd_functions

prompt_spaceship_chpwd "$@"
