#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Hook to save exit code and prepare prompts
function prompt_spaceship_precmd() {
  # Retrieve exit code of last command to use in exit_code
  # Must be captured before any other command in prompt is executed
  # Must be the very first line in all entry prompt functions, or the value
  # will be overridden by a different command execution - do not move this line!
  RETVAL=$?
  RETVALS=( "$pipestatus[@]" )

  run-ss-hook precmd

  # Restarts the async worker, in order to get an update-to-date shell environment
  if [[ "${_SS_DATA[async]}" == "true" ]]; then
    async_stop_worker "spaceship_section_worker"
    async_start_worker "spaceship_section_worker" #-n
    # setopt before call register to avoid callback by async_worker_eval
    async_worker_eval "spaceship_section_worker" 'setopt EXTENDED_GLOB'
    async_register_callback "spaceship_section_worker" "ss::async_callback"
  fi

  ss::build_section_cache
}

typeset -ag ss_precmd_functions

prompt_spaceship_precmd "$@"
