#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

function prompt_spaceship_preexec {
  # Stop running prompt async jobs
  if [[ "${_SS_DATA[async]}" == "true" ]]; then
    async_flush_jobs "spaceship_section_worker"
  fi

  run-ss-hook preexec
}

typeset -ag ss_preexec_functions

prompt_spaceship_preexec "$@"
