#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Refresh a single item in the cache, and redraw the prompt
#
# @args
#   $1 - section name
#   $2 - boolean true if render the prompt after cache update
function ss::refresh_cache_item() {
  [[ -z $1 ]] && return 1

  local section="$1"
  local alignment
  local cache result

  if ss::section_in_use "${section}" "prompt"; then
    alignment="prompt"
  elif ss::section_in_use "${section}" "rprompt"; then
    alignment="rprompt"
  else
    # Unavailable section name
    return 1
  fi

  [[ "${_ss_async_sections[${section}]}" == "true" ]] && async=true || async=false

  cache_key="${alignment}::${section}"

  if ${async}; then
    async_job "spaceship_async_worker" "ss::async_wrapper" "ss::${section}" "${section}·|·${alignment}·|·"

    # Placeholder
    _ss_section_cache[${cache_key}]="${section}·|·${alignment}·|·${SPACESHIP_SECTION_PLACEHOLDER}"
  else
    _SS_DATA[section_result]=""
    ss::${section}
    _ss_section_cache[${cache_key}]="${section}·|·${alignment}·|·${_SS_DATA[section_result]}"

    [[ $2 == "true" ]] && ss::render "$alignment"
  fi
}

ss::refresh_cache_item "$@"
