#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# BACKWARD COMPATIBILITY WARNINGS
# Show deprecation messages for options that are set, but not supported

function ss::deprecated_check {
  ss::deprecated SPACESHIP_PROMPT_SYMBOL "Use %BSPACESHIP_CHAR_SYMBOL%b instead."
  ss::deprecated SPACESHIP_BATTERY_ALWAYS_SHOW "Use %BSPACESHIP_BATTERY_SHOW='always'%b instead."
  ss::deprecated SPACESHIP_BATTERY_CHARGING_SYMBOL "Use %BSPACESHIP_BATTERY_SYMBOL_CHARGING%b instead."
  ss::deprecated SPACESHIP_BATTERY_DISCHARGING_SYMBOL "Use %BSPACESHIP_BATTERY_SYMBOL_DISCHARGING%b instead."
  ss::deprecated SPACESHIP_BATTERY_FULL_SYMBOL "Use %BSPACESHIP_BATTERY_SYMBOL_FULL%b instead."
  # New deprecation added in 4.x
  if (( $+functions[ss::git] )) || (( $+functions[ss::git_branch])) || (( $+functions[ss::git_status] )) \
    || (( $+functions[ss::hg] )) || (( $+functions[ss::hg_branch])) || (( $+functions[ss::hg_status] )); then
    print -P "%{%B%}git and hg%{%b%} are deprecated. Use section %{%B%}vcs%{%b%} instead. Check the doc for detail."
  fi
  if (( $+functions[ss::vi_mode] )); then
    print -P "%{%B%}vi_mode%{%b%} is deprecated and integrated into %{%B%}char%{%b%}. Check the doc for detail."
  fi
}

ss::deprecated_check "$@"
