#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Draw prompt section (bold is used as default)
# USAGE:
#   sz::section <color> <content> [prefix] [suffix]
function sz::section {
  local color content prefix suffix

  local prompt_opened result=""

  [[ -n $1 ]] && color="%F{$1}" || color="%f"
  content="$2"
  prefix="$3"
  suffix="$4"

  source "${_SS_DATA[section_var_file]}"

  if [[ $prompt_opened == true ]] \
    && [[ $SPACESHIP_PROMPT_PREFIXES_SHOW == true ]] \
    && [[ -n "$prefix" ]]; then
    # set prefix bold
    result+="%{%B%}${prefix}%{%b%}"
  fi
  echo "prompt_opened=true" >| "${_SS_DATA[section_var_file]}"
  result+="%{%B${color}%}" # set color
  result+="$content"       # section content
  result+="%{%b%f%}"       # unset color

  if [[ $SPACESHIP_PROMPT_SUFFIXES_SHOW == true ]] \
    && [[ -n "$suffix" ]]; then
    # reset bold, if it was diabled before
    result+="%{%B%}${suffix}%{%b%}"
  fi

  # pass the result out with the global variable
  _SS_DATA[section_result]="$result"
}

sz::section "$@"
