#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

#
# Ruby
#
# A dynamic, reflective, object-oriented, general-purpose programming language.
# Link: https://www.ruby-lang.org/

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

SPACESHIP_RUBY_SHOW="${SPACESHIP_RUBY_SHOW=true}"
SPACESHIP_RUBY_PREFIX="${SPACESHIP_RUBY_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_RUBY_SUFFIX="${SPACESHIP_RUBY_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_RUBY_SYMBOL="${SPACESHIP_RUBY_SYMBOL="💎 "}"
SPACESHIP_RUBY_COLOR="${SPACESHIP_RUBY_COLOR="red"}"

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

# Show current version of Ruby
sz::ruby() {
  [[ $SPACESHIP_RUBY_SHOW == false ]] && return

  (( $+commands[rbenv] )) || (( $+commands[rvm-prompt] )) \
    || (( $+commands[chruby] )) || (( $+commands[asdf] )) \
    || return

  # Show versions only for Ruby-specific folders
  [[ -n $RBENV_VERSION ]] \
    || sz::upsearch ".ruby-version" >/dev/null \
    || sz::upsearch "Gemfile" >/dev/null \
    || sz::upsearch "Rakefile" >/dev/null \
    || [[ -n *.rb(#qN^/) ]] \
    || return

  local 'ruby_version'

  if (( $+commands[rvm-prompt] )); then
    ruby_version=$(rvm-prompt i v g)
  elif (( $+commands[chruby] )); then
    ruby_version=$(chruby | sed -n -e 's/ \* //p')
  elif (( $+commands[rbenv] )); then
    ruby_version=$(rbenv version-name)
  elif (( $+commands[asdf] )); then
    # split output on space and return first element
    ruby_version=${$(asdf current ruby)[1]}
  else
    return
  fi

  [[ -z $ruby_version || "${ruby_version}" == "system" ]] && return

  # Add 'v' before ruby version that starts with a number
  [[ "${ruby_version}" =~ ^[0-9].+$ ]] && ruby_version="v${ruby_version}"

  sz::section \
    "$SPACESHIP_RUBY_COLOR" \
    "${SPACESHIP_RUBY_SYMBOL}${ruby_version}" \
    "$SPACESHIP_RUBY_PREFIX" \
    "$SPACESHIP_RUBY_SUFFIX"
}

sz::ruby "$@"
