#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

#
# Package
#
# Current package version.
# These package managers supported:
#   * npm
#   * Lerna
#   * Cargo
#   * Composer
#   * Julia

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

SPACESHIP_PACKAGE_SHOW="${SPACESHIP_PACKAGE_SHOW=true}"
SPACESHIP_PACKAGE_SHOW_PRIVATE="${SPACESHIP_PACKAGE_SHOW_PRIVATE=false}"
SPACESHIP_PACKAGE_PREFIX="${SPACESHIP_PACKAGE_PREFIX="is "}"
SPACESHIP_PACKAGE_SUFFIX="${SPACESHIP_PACKAGE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_PACKAGE_SYMBOL="${SPACESHIP_PACKAGE_SYMBOL="📦 "}"
SPACESHIP_PACKAGE_COLOR="${SPACESHIP_PACKAGE_COLOR="red"}"
if [ -z "$SPACESHIP_PACKAGE_ORDER" ]; then
  SPACESHIP_PACKAGE_ORDER=(npm lerna cargo composer julia)
fi

# ------------------------------------------------------------------------------
# Package Managers
# ------------------------------------------------------------------------------

sz::package() {
  [[ $SPACESHIP_PACKAGE_SHOW == false ]] && return

  # Show package version only when repository is a package
  local package_path package_version manager pkgid

  for manager in "${SPACESHIP_PACKAGE_ORDER[@]}"; do
    case "$manager" in
      npm)
        (( $+commands[npm] )) || continue
        package_path="$(sz::upsearch package.json file self)" || continue
        if [[ "$SPACESHIP_PACKAGE_SHOW_PRIVATE" == false ]] \
          && [[ "$(sz::datafile "$package_path" private)" == true ]]; then
          break
        fi
        package_version="$(sz::datafile "$package_path" version)"
        if [[ "$package_version" == "0.0.0-development" ]] \
          || [[ $package_version == "0.0.0-semantic"* ]]; then
          package_version="(semantic)"
        fi
      ;;
      lerna)
        # Show package version from lerna.json if is a lerna monorepo
        # Note: lerna does not have to be installed in the global context
        # so checking for lerna binary does not make sense
        (( $+commands[npm] )) || continue
        package_path="$(sz::upsearch lerna.json file self)" || continue
        package_version="$(sz::datafile "$package_path" version)"
        if [[ "$package_version" == "independent" ]]; then
          package_version="($package_version)"
        fi
      ;;
      cargo)
        # Handle missing field `version` in Cargo.toml.
        # `cargo pkgid` need Cargo.lock exists too. If it does't, do not show package version
        # https://github.com/spaceship-prompt/spaceship-prompt/pull/617
        (( $+commands[cargo] )) || continue
        package_path="$(sz::upsearch Cargo.toml file self)" || continue
        pkgid="$(cargo pkgid 2>&1)"
        echo "$pkgid" | grep -q "error:" && continue
        package_version="${pkgid##*\#}"
      ;;
      composer)
        (( $+commands[composer] )) || continue
        package_path="$(sz::upsearch composer.json file self)" || continue
        package_version="$(sz::datafile "$package_path" version)"
      ;;
      julia)
        (( $+commands[julia] )) || continue
        package_path="$(sz::upsearch Project.toml file self)" || continue
        package_version="$(sz::datafile "$package_path" version)"
      ;;
    esac
    [[ -z $package_version ]] || [[ "$package_version" == "null" ]] \
      || [[ "$package_version" == "undefined" ]] || break
  done

  [[ -z $package_version || "$package_version" == "null" || "$package_version" == "undefined" ]] && return
  sz::section \
    "$SPACESHIP_PACKAGE_COLOR" \
    "${SPACESHIP_PACKAGE_SYMBOL}v${package_version}" \
    "$SPACESHIP_PACKAGE_PREFIX" \
    "$SPACESHIP_PACKAGE_SUFFIX"
}

sz::package "$@"
