#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

#
# Line separator
#

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

# Should it write prompt in two lines or not?
sz::line_sep() {
  local NEWLINE=$'\n'
  [[ $SPACESHIP_PROMPT_SEPARATE_LINE == true ]] && _SS_DATA[section_result]="$NEWLINE"
}

sz::line_sep "$@"
