#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

#
# Gradle
#
# Gradle is an open-source build automation tool focused on flexibility and performance.
# Link: https://gradle.org/

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

SPACESHIP_GRADLE_SHOW="${SPACESHIP_GRADLE_SHOW=true}"
SPACESHIP_GRADLE_PREFIX="${SPACESHIP_GRADLE_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_GRADLE_SUFFIX="${SPACESHIP_GRADLE_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_GRADLE_SYMBOL="${SPACESHIP_GRADLE_SYMBOL="⬡ "}"
SPACESHIP_GRADLE_DEFAULT_VERSION="${SPACESHIP_GRADLE_DEFAULT_VERSION=""}"
SPACESHIP_GRADLE_COLOR="${SPACESHIP_GRADLE_COLOR="green"}"

SPACESHIP_GRADLE_JVM_SHOW="${SPACESHIP_GRADLE_JVM_SHOW=true}"
SPACESHIP_GRADLE_JVM_PREFIX="${SPACESHIP_GRADLE_JVM_PREFIX="$SPACESHIP_PROMPT_DEFAULT_PREFIX"}"
SPACESHIP_GRADLE_JVM_SUFFIX="${SPACESHIP_GRADLE_JVM_SUFFIX="$SPACESHIP_PROMPT_DEFAULT_SUFFIX"}"
SPACESHIP_GRADLE_JVM_SYMBOL="${SPACESHIP_GRADLE_JVM_SYMBOL="☕️ "}"
SPACESHIP_GRADLE_JVM_DEFAULT_VERSION="${SPACESHIP_GRADLE_JVM_DEFAULT_VERSION=""}"
SPACESHIP_GRADLE_JVM_COLOR="${SPACESHIP_GRADLE_JVM_COLOR="magenta"}"

# ------------------------------------------------------------------------------
# Utils
# ------------------------------------------------------------------------------
sz::gradle::versions() {
  local gradle_exe="$1" gradle_version_output gradle_version jvm_version

  gradle_version_output=$("$gradle_exe" --version)
  gradle_version=$(<<< "$gradle_version_output" command awk '{ if ($1 ~ /^Gradle/) { print "v" $2 } }')
  jvm_version=$(<<< "$gradle_version_output" command awk '{ if ($1 ~ /^JVM:/) { print "v" $2 } }')

  print gradle "$gradle_version" jvm "$jvm_version"
}

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

# Show current version of gradle.
sz::gradle() {
  [[ $SPACESHIP_GRADLE_SHOW == false ]] && return

  local gradle_root_dir

  gradle_root_dir="$(sz::upsearch settings.gradle)" \
    || gradle_root_dir="$(sz::upsearch settings.gradle.kts)" \
    || return

  local -A gradle_versions

  if [[ -f "$gradle_root_dir/gradlew" ]]; then
    gradle_versions=($(sz::gradle::versions "$gradle_root_dir/gradlew"))
  elif (( $+commands[gradle] )); then
    gradle_versions=($(sz::gradle::versions gradle))
  else
    return
  fi

  [[ "${gradle_versions[gradle]}" == "$SPACESHIP_GRADLE_DEFAULT_VERSION" ]] && return

  local jvm_info

  if [[ $SPACESHIP_GRADLE_JVM_SHOW == false ]] || \
    [[ "${gradle_versions[jvm]}" == "$SPACESHIP_GRADLE_JVM_DEFAULT_VERSION" ]]; then
    jvm_info=""
  else
    _SS_DATA[section_result]=""
    sz::section \
      "$SPACESHIP_GRADLE_JVM_COLOR" \
      "$SPACESHIP_GRADLE_JVM_SYMBOL${gradle_versions[jvm]}" \
      "$SPACESHIP_GRADLE_JVM_PREFIX" \
      "$SPACESHIP_GRADLE_JVM_SUFFIX"
    jvm_info="${_SS_DATA[section_result]}"
  fi

  sz::section \
    "$SPACESHIP_GRADLE_COLOR" \
    "$SPACESHIP_GRADLE_SYMBOL${gradle_versions[gradle]}$SPACESHIP_GRADLE_SUFFIX`
    `${jvm_info}" \
    "$SPACESHIP_GRADLE_PREFIX"
}

sz::gradle "$@"
