#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

#
# Prompt character
#

# ------------------------------------------------------------------------------
# Configuration
# ------------------------------------------------------------------------------

SPACESHIP_VI_MODE_SHOW="${SPACESHIP_VI_MODE_SHOW=true}"
SPACESHIP_VI_MODE_INSERT="${SPACESHIP_VI_MODE_INSERT="❯ "}"
SPACESHIP_VI_MODE_NORMAL="${SPACESHIP_VI_MODE_NORMAL="❮ "}"

SPACESHIP_CHAR_PREFIX="${SPACESHIP_CHAR_PREFIX=""}"
SPACESHIP_CHAR_SUFFIX="${SPACESHIP_CHAR_SUFFIX=""}"
SPACESHIP_CHAR_SYMBOL="${SPACESHIP_CHAR_SYMBOL="$SPACESHIP_VI_MODE_INSERT"}"
SPACESHIP_CHAR_SYMBOL_ROOT="${SPACESHIP_CHAR_SYMBOL_ROOT="$SPACESHIP_CHAR_SYMBOL"}"
SPACESHIP_CHAR_SYMBOL_SECONDARY="${SPACESHIP_CHAR_SYMBOL_SECONDARY="..."}"
SPACESHIP_CHAR_COLOR_SUCCESS="${SPACESHIP_CHAR_COLOR_SUCCESS="green"}"
SPACESHIP_CHAR_COLOR_FAILURE="${SPACESHIP_CHAR_COLOR_FAILURE="red"}"
SPACESHIP_CHAR_COLOR_SECONDARY="${SPACESHIP_CHAR_COLOR_SECONDARY="yellow"}"

sz::set_default SPACESHIP_VI_MODE_CURSOR "true"
sz::set_default SPACESHIP_VI_MODE_CURSOR_NORMAL "block"
sz::set_default SPACESHIP_VI_MODE_CURSOR_INSERT "blinking bar"

# ------------------------------------------------------------------------------
# Section
# ------------------------------------------------------------------------------

# Paint $PROMPT_SYMBOL in red if previous command was fail and
# paint in green if everything was OK.
sz::char() {
  local color char

  if [[ $RETVAL -eq 0 ]]; then
    color="$SPACESHIP_CHAR_COLOR_SUCCESS"
  else
    color="$SPACESHIP_CHAR_COLOR_FAILURE"
  fi

  # http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#User_002dDefined-Widgets
  if [[ $SPACESHIP_VI_MODE_SHOW == true ]] && [[ -n $KEYMAP ]]; then
    char="${SPACESHIP_VI_MODE_INSERT}"

    case "${KEYMAP}" in
      main|viins)
      char="${SPACESHIP_VI_MODE_INSERT}"
      ;;
      vicmd)
      char="${SPACESHIP_VI_MODE_NORMAL}"
      ;;
    esac

  else
    if [[ $UID -eq 0 ]]; then
      char="$SPACESHIP_CHAR_SYMBOL_ROOT"
    else
      char="$SPACESHIP_CHAR_SYMBOL"
    fi
  fi

  sz::section \
    "$color" \
    "$char" \
    "$SPACESHIP_CHAR_PREFIX" \
    "$SPACESHIP_CHAR_SUFFIX"
}

# Init
track-sz-autoload add-zle-hook-widget sz::vi_mode_setup sz::vi_mode_cleanup

if [[ $SPACESHIP_VI_MODE_SHOW == true ]]; then
  sz::vi_mode_setup
fi

sz::char "$@"
