#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et
#
# https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples

# git: Show remote branch name for remote-tracking branches
function +vi-git-remotebranch {
  local remote

  # Are we on a remote-tracking branch?
  remote=${$(git rev-parse --verify ${hook_com[branch]}@{upstream} \
    --symbolic-full-name 2>/dev/null)/refs\/remotes\/}

  # The first test will show a tracking branch whenever there is one. The
  # second test, however, will only show the remote branch's name if it
  # differs from the local one.
  if [[ -n "$remote" ]] ; then
  #if [[ -n ${remote} && ${remote#*/} != ${hook_com[branch]} ]] ; then
    hook_com[branch]="${hook_com[branch]} [${remote}]"
  fi
}

+vi-git-remotebranch "$@"
