#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et
#
# spacezsh/sections/hg_status

function +vi-hg-deleted {
  [[ -n "${hook_com[index]}" ]] || hook_com[index]=$(command hg status 2>/dev/null)

  if <<< "${hook_com[index]}" command grep -E '^(R|!)' &> /dev/null; then
    hook_com[unstaged]+="${SPACESHIP_VCS_DELETED}"
  fi
}

+vi-hg-deleted "$@"
