#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Change cursor shape according to current vi_mode
function ss::vi_mode_cursor_switch {
  # TODO: make char style compatible with more terminals
  if [[ $KEYMAP = vicmd ]]; then
    # block symbol for command mode
    echo -ne "\e[2 q"
  else
    # pipe symbol for insert mode
    echo -ne "\e[6 q"
  fi
}

ss::vi_mode_cursor_switch "$@"
