#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Enables terminal application mode and updates editor information.
function ss::vi-mode-line-init {
  # prezto/modules/completion
  # The terminal must be in application mode when ZLE is active for $terminfo
  # values to be valid.
  if (( $+terminfo[smkx] )); then
    # Enable terminal application mode.
    echoti smkx
  fi

  # rerender prompt to get vi mode updated
  ss::refresh_cache_item "vi_char" "true"

  ss::vi_mode_cursor_switch
}

ss::vi-mode-line-init "$@"
