#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Enable vi mode and update the indicator in prompt
function ss::vi_mode_setup {
  local item

  # http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions
  # http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Special-Widgets
  track-ss-autoload add-zle-hook-widget

  # Setup widget to update mode status in prompt
  for item in keymap-select line-init line-finish; do
    track-ss-autoload ss::vi-mode-${item}
    add-zle-hook-widget -Uz $item ss::vi-mode-${item}
  done

  bindkey -v
}

ss::vi_mode_setup "$@"
