#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Updates editor information when the keymap changes.
function ss::vi-mode-keymap-select {
  # Re-render prompt to get vi mode updated
  ss::refresh_cache_item "vi_char" "true"

  # Update cursor style
  case "$KEYMAP" in
    vicmd|visual|vline)
      ss::set_cursor_style ${(s. .)SPACESHIP_VI_MODE_CURSOR_VICMD}
      ;;
    main|viins|*)
      ss::set_cursor_style ${(s. .)SPACESHIP_VI_MODE_CURSOR_VIINS}
      ;;
  esac
}

ss::vi-mode-keymap-select "$@"
