#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Check if function is defined
# USAGE:
#   ss::func_defined <function>
function ss::func_defined {
  typeset -f + "$1" &> /dev/null
}

ss::func_defined "$@"
