#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et
#
# Borrowed from p9k

###############################################################
# @description
#   This function determine if a variable has been previously defined,
#   and only sets the value to the specified default if it hasn't.
##
# @args
#   $1 string The name of the variable that should be checked.
#   $2 string The default value.
##
# @returns
#   Nothing.
##
# @note
#   Typeset cannot set the value for an array, so this will only work
#   for scalar values.
##
function ss::set_default() {
  local varname="$1"
  local default_value="$2"

  [[ -n "${(tP)varname:-}" ]] || typeset -g "$varname"="$default_value"
}

ss::set_default "$@"
