#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et

# Enable vi mode and update the indicator in prompt
function sz::vi_mode_setup {
  local item

  # http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions
  # http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Special-Widgets
  track-sz-autoload add-zle-hook-widget

  # Setup widget to update mode status in prompt
  for item in keymap-select; do
    track-sz-autoload sz::vi-mode-${item}
    add-zle-hook-widget -Uz $item sz::vi-mode-${item}
  done

  # No idea why zle hook widgets break shells in poetry, pipenv
  # TODO: warn users to set VIM_MODE_TRACK_KEYMAP="no" ?
  if [[ $VIM_MODE_TRACK_KEYMAP == "no" ]] \
    || {[[ -z $POETRY_ACTIVE ]] && [[ -z $PIPENV_ACTIVE ]]}; then
    for item in line-init line-finish; do
      track-sz-autoload sz::vi-mode-${item}
      add-zle-hook-widget -Uz $item sz::vi-mode-${item}
    done
  fi

  bindkey -v
}

sz::vi_mode_setup "$@"
