#!/usr/bin/env zsh
# vim: ft=zsh fdm=marker foldlevel=0 sw=2 ts=2 sts=2 et
#
# References
#   https://github.com/softmoth/zsh-vim-mode

function sz::send_terminal_sequence {
    local sequence="$1"

    # Older TMUX (before 1.5) does not handle cursor styling and needs
    # to be told to pass those escape sequences directly to the terminal
    if [[ $TMUX_PASSTHROUGH = 1 ]]; then
        # Double each escape (see zshbuiltins(1) echo for backslash escapes)
        # And wrap it in the TMUX DCS passthrough
        sequence=${sequence//\\(e|x27|033|[uU]00*1[bB])/\\e\\e}
        sequence="\ePtmux;$sequence\e\\"
    fi
    print -n "$sequence"
}

sz::send_terminal_sequence "$@"
